apiVersion: apps/v1
kind: Deployment
metadata:
  name: statsd-exporter
  namespace: monitoring
  labels:
    app: statsd-exporter
spec:
  replicas: 1
  selector:
    matchLabels:
      app: statsd-exporter
  template:
    metadata:
      labels:
        app: statsd-exporter
    spec:
      containers:
        - name: statsd-exporter
          image: prom/statsd-exporter:latest
          ports:
            - containerPort: 9125
              protocol: UDP
          args:
            - "--statsd.listen-udp=:9125"
---
apiVersion: v1
kind: Service
metadata:
  name: statsd-exporter
  namespace: monitoring
spec:
  selector:
    app: statsd-exporter
  ports:
    - name: udp
      port: 9125
      protocol: UDP